Mdoc datamodel
italia/eidas-it-wallet-docs pull request #166
Opened 2023-11-13 12:08 UTC by fmarino-ipzs

## MDOC-CBOR Data Model

## Content
This PR closes #18 

## Review

- [x] Ensure your files are written following RST specs (*not MD!*)
- [ ] Italian version
- [x] English version
- [ ] Example files 
- [x] Ask for review

2023-11-13 12:16 UTC, grausof approved these changes
LGTM

2023-11-13 17:25 UTC, peppelinux requested changes

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
>  The (Q)EAAs are extended according to the `OpenID Identity Assurance Profile [OIDC.IDA] <https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html>`_, that allows the recipients to kno
```suggestion
The (Q)EAAs are extended according to `OpenID Identity Assurance Profile [OIDC.IDA] <https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html>`_, that allows the recipients to know the Authentic Sources where the data comes from. 
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The PID MDOC-CBOR document type uses the namespace `eu.europa.ec.eudiw.pid.1`, according to the reverse domain approach defined in the
```suggestion
The PID encoded in MDOC-CBOR format uses the document type set to `eu.europa.ec.eudiw.pid.1`, according to the reverse domain approach defined in the 
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +`EIDAS-ARF`_ and in fully harmonization with the ISO/IEC 18013-5 standard.
```suggestion
`EIDAS-ARF`_ and ISO/IEC 18013-5.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The the data elements contained in the document, use the same namespace for the required PID attributes, while the national PID attributes use the domestic namespace `eu.europa.ec.eudiw.pid.it.1`, de
```suggestion
The document's data elements utilize a consistent namespace for the mandatory Mobile Driving License attributes, while the national PID attributes use the domestic namespace `eu.europa.ec.eudiw.pid.it.1`, as outlined in this implementation profile.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +According to ISO/IEC 18013-5, the structure of MDOC response that is encoded in CBOR MUST be as the following:
```suggestion
In compliance with ISO/IEC 18013-5, the MDOC data model in the domestic namespace `eu.europa.ec.eudiw.pid.it.1`, requires the following attributes:
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *tstr (text string)*. Version of the PID/(Q)EAA structures. For example, ``"version":"1.0"`` means that this is the first version of PID/(Q)EAA ISO-compliant attestation.
```suggestion
      - *tstr (text string)*. Version of the data structure being used. It's a way to track changes and updates to the standard or to a specific implementation profile. This allows for backward compatibility and understanding of the data if the standard or implementation evolves over time.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Returned documents. For example, PID/(Q)EAA.
```suggestion
      - *bstr (byte string)*. The collection of digital documents. Each document in this collection represents a specific type of data or information related to the Digital Credential.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The **documents** object contains the Digital Credential and it MUST have the following structure:
```suggestion
Each document within the **documents** collection MUST have the following structure:
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *tstr (text string)*. Document type returned. For example for the PID, the value MUST be ``eu.europa.ec.eudiw.pid.1.`` For an mDL, the value MUST be ``org.iso.18013-5.1.mDL``.
```suggestion
      - *tstr (text string)*. Document type. For the PID, the value MUST be set to ``eu.europa.ec.eudiw.pid.1.`` For an mDL, the value MUST be ``org.iso.18013-5.1.mDL``.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Returned data elements signed by the Issuer.
@fmarino-ipzs even if it is called issuerSigned the elements contained in it are not signed.
Then we should say who's the issuer, its content may vary if the issuer is the credential issuer (containing all the disclosure) or the wallet instance, containing just the selected disclosed attributes

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)* with *tag* 24 and *major type* 6. Returned data elements for the namespaces. It MAY be possible to have one or more namespaces. The nameSpaces MUST use the same value for
```suggestion
      - *bstr (byte string)* with *tag* 24 and *major type* 6. Returned data elements for the namespaces. It MAY be possible to have one or more namespaces. The `nameSpaces` MUST use the same value for the document type. However, it MAY have a domestic namespace to include attributes defined in this implementation profile. The value MUST be set to ``eu.europa.ec.eudiw.pid.it.1``.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Contains *Mobile Security Object* (MSO) for issuer data authentication.
```suggestion
      - *bstr (byte string)*. Contains *Mobile Security Object* (MSO), a COSE Sign1 Document, issued by the Credential Issuer.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +During the presentation of a credential in MDOC-CBOR format, in addition to the objects in the table above, a **deviceSigned** object MUST also be added and MUST NOT be present in the issued credenti
```suggestion
During the presentation of the MDOC-CBOR credential, in addition to the objects in the table above, a **deviceSigned** object MUST also be added. **deviceSigned** MUST NOT be included in the issued credential provided by the PID/(Q)EAA Issuer.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Contains the device authentication for MDOC data authentication.
we can improve this wording as well.

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +    1. Provide Optional self-attested claims in the ``nameSpaces`` object. Even if no self-attested claims are provided by the Wallet Instance, the ``nameSpaces`` object MUST be included with an empt
```suggestion
    1. It provides optional self-attested attributes in the ``nameSpaces`` object. If no self-attested attributes are provided by the Wallet Instance, the ``nameSpaces`` object MUST be included with an empty structure.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +    2. Provide a cryptographic proof that the Holder is the legitimate owner of the Credential by means of a ``deviceAuth`` object.
```suggestion
    2. Provide a cryptographic proof attesting that the Holder is the legitimate owner of the Credential, by means of a ``deviceAuth`` object. 
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +    The ``issuerSigned`` and the ``deviceSigned`` objects contain the ``nameSpaces`` object and the *Mobile Security Object*. The latter is the only signed object, while the ``nameSpaces`` object is
I agree, therefore, having said that `The latter is the only signed object` we should change the definition text of `issuerSigned` (see my previous comment)

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The **nameSpaces** object contains one or more *IssuerSignedItemBytes* that are encoded using CBOR bitsring 24 tag (#6.24(bstr .cbor), Marked with 24(<<... >>) in the example), representing the discl
```suggestion
The **nameSpaces** object contains one or more *IssuerSignedItemBytes* that are encoded using CBOR bitsring 24 tag (#6.24(bstr .cbor), marked with the CBOR Tag 24(<<... >>) and represented in the example using the diagnostic format). It represents the disclosure information for each digest within the `Mobile Security Object` and MUST contain the following attributes:
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - This value is a reference to the equivalent hash value within ``ValueDigests`` in the *Mobile Security Object*.
```suggestion
      - Reference value to one of the ``ValueDigests`` provided in the *Mobile Security Object* (`issuerAuth`).
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - Random byte value used as salt for the hash function. This value shall be different for each *IssuerSignedItem* and shall have a minimum length of 16 bytes.
```suggestion
      - Random byte value used as salt for the hash function. This value SHALL be different for each *IssuerSignedItem* and it SHALL have a minimum length of 16 bytes.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +
```suggestion
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +Depending on the Digital Credential type, additional **elementIdentifier** data MAY be added. For the PID it MUST support the following data:
```suggestion
Depending on the Digital Credential type, additional **elementIdentifier** data MAY be added. The PID MUST support the following data:
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The **issuerAuth** MUST contain a `Mobile Security Object` which is an untagged value containing a `COSE Sign1 Document`, as defined in `RFC 9052 - CBOR Object Signing and Encryption (COSE): Structur
```suggestion
The **issuerAuth** represents the `Mobile Security Object` which is a `COSE Sign1 Document` defined in `RFC 9052 - CBOR Object Signing and Encryption (COSE): Structures and Process <https://www.rfc-editor.org/rfc/rfc9052.html>`_. It has the following data structure:
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +    The `x5chain` is included in the unprotected header with the aim to make the Holder able to update the X.509 certificate chain, related to the `Mobile Security Object` issuer, without breaking th
```suggestion
    The `x5chain` is included in the unprotected header with the aim to make the Holder able to update the X.509 certificate chain, related to the `Mobile Security Object` issuer, without corrupting the signature.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The **payload** MUST contain the *MobileSecurityObject*, without any `content-type` definition, encoded as a *byte string* (bstr) with *CBOR Tag* 24.
```suggestion
The **payload** MUST contain the *MobileSecurityObject*, without the `content-type` COSE Sign header parameter and encoded as a *byte string* (bstr) using the *CBOR Tag* 24.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - It MUST be set to the public key that is generated by the Wallet Instance. It contains the following sub-values.
```suggestion
      - It MUST contain the Wallet Instance's public key contains the following sub-values.
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +      - It MUST be set to the public key that is generated by the Wallet Instance. It contains the following sub-values.
if we say that contains the pkey we then cannot say that contains sub attributes, a rewording is then required.

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +    The private key related to the public key stored in the `deviceKey` object, is used to authenticate the PID during the presentation phase, where the `DeviceSignedItems` structure is involved (see
```suggestion
    The private key related to the public key stored in the `deviceKey` object is used to sign the `DeviceSignedItems` object and proof the possession of the PID during the presentation phase (see the presentation phase with MDOC-CBOR).
```

2023-11-13 17:25 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +A PID in MDOC-CBOR is represented below in AF Binary format:
```suggestion
A non-normative example of a PID in MDOC-CBOR format is represented below using the AF Binary encoding:
```

2023-11-14 16:19 UTC, fmarino-ipzs commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Returned data elements signed by the Issuer.
```suggestion
      - *bstr (byte string)*. It MUST contain the Mobile Security Object for Issuer data authentication and the data elements protected by Issuer data authentication.
```

2023-11-14 16:19 UTC, fmarino-ipzs commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Contains the device authentication for MDOC data authentication.
```suggestion
      - *bstr (byte string)*. It MUST contain either the *DeviceSignature* or the *DeviceMac* element.
```

2023-11-14 16:19 UTC, fmarino-ipzs commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Returned data elements signed by the Issuer.
@peppelinux , check if it sounds good to you now.

2023-11-14 16:19 UTC, fmarino-ipzs commented on docs/en/pid-eaa-data-model.rst
> +      - *bstr (byte string)*. Contains the device authentication for MDOC data authentication.
@peppelinux , check please

2023-11-14 16:19 UTC, fmarino-ipzs commented on docs/en/pid-eaa-data-model.rst
> +    The ``issuerSigned`` and the ``deviceSigned`` objects contain the ``nameSpaces`` object and the *Mobile Security Object*. The latter is the only signed object, while the ``nameSpaces`` object is
I modified the definitions, check if now it is more clear.

2023-11-14 16:23 UTC, fmarino-ipzs commented on docs/en/pid-eaa-data-model.rst
> +In compliance with ISO/IEC 18013-5, the MDOC data model in the domestic namespace `eu.europa.ec.eudiw.pid.it.1`, requires the following attributes:
@peppelinux, checking again the ISO it seems that a domestic namespace should be eu.europa.ec.eudiw.pid.1.IT instead of eu.europa.ec.eudiw.pid.it.1. 
WDYT?

2023-11-23 14:57 UTC, peppelinux commented
@fmarino-ipzs introducing mdoc cbor has impacts on the issuance, `credential_definition` must use `doctype` instead of `type` or `vct`

2023-11-23 15:12 UTC, peppelinux approved these changes

2023-11-23 15:16 UTC, peppelinux approved these changes

2023-11-23 15:16 UTC, fmarino-ipzs commented
> @fmarino-ipzs introducing mdoc cbor has impacts on the issuance, `credential_definition` must use `doctype` instead of `type` or `vct`

I think that the Issuance protocol should be credential format agnostic. Otherwise, we have to parse the credential_definition claim according to the format one. The format should refer to the credential and not to the JSON which conveys the credential_definition claim.

2023-11-23 15:17 UTC, merged

2023-11-23 15:25 UTC, peppelinux commented
@fmarino-ipzs it's not our choice, this comes from the standards OpenID4VC and HAIP