[Issuance flow]: added error management
italia/eidas-it-wallet-docs pull request #225
Opened 2024-03-01 22:55 UTC by fmarino-ipzs

## Title
[Issuance flow]: added error management

## Content
In this PR I clarify how to handle the HTTP Error Response in case of an invalid
- PAR Request
- Authorization Request
- Token Request
- Credential Request

I also fixed some typos (link to the OID4VCI, reference to a table) and I made some minor editorial fixes. 

This PR closes #139 

## Review

- [x] Ensure your files are written following RST specs (*not MD!*)
- [ ] Italian version
- [x] English version
- [x] Example files 
- [x] Ask for review

2024-03-02 20:10 UTC, peppelinux commented on docs/en/pid-eaa-issuance.rst
> +  Cache-Control: no-cache, no-store
```suggestion
```

2024-03-02 20:21 UTC, peppelinux requested changes

2024-03-02 20:21 UTC, peppelinux commented on docs/en/pid-eaa-issuance.rst
> +  - *error_description*. Text in human-readable form providing further details to clarify the nature of the error encountered.
```suggestion
If any errors occur during the validation of the Token Request, the Authorization Server MUST return an error response as defined in :rfc:`6749#section-5.2`.
```

già detto prima, vuoi ripeterlo anche qui?

2024-03-02 20:21 UTC, peppelinux commented on docs/en/pid-eaa-issuance.rst
> +    - `[OIDC4VCI. Draft 13] <https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html>`_.
vedo questo link riportato spesso, che ne pensi se registrassimo un tag e andassimo by ref?

2024-03-02 20:21 UTC, peppelinux commented on docs/en/pid-eaa-issuance.rst
> +  - *error_description*. Text in human-readable form providing further details to clarify the nature of the error encountered.
come prima

2024-03-02 20:32 UTC, fmarino-ipzs commented on docs/en/pid-eaa-issuance.rst
> +    - `[OIDC4VCI. Draft 13] <https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html>`_.
Sì ci avevo pensato anche perché sarebbe più comodo nel caso di eventuali future modifiche della url. Appena riesco lo faccio

2024-03-04 09:56 UTC, balanza approved these changes

2024-03-04 10:01 UTC, peppelinux approved these changes

2024-03-04 10:01 UTC, merged