fix: Wallet Attestation response code and method
italia/eidas-it-wallet-docs pull request #287
Opened 2024-05-23 09:16 UTC by grausof

This PR aligns the Wallet Attestation request with the REST specification

2024-05-23 09:47 UTC, peppelinux approved these changes

2024-05-29 10:08 UTC, fmarino-ipzs requested changes
Please, add the normative text according to the non normative examples

2024-06-17 10:00 UTC, grausof commented
> Please, add the normative text according to the non normative examples

Can you give an example? Originally there was no other additional text

2024-06-17 10:27 UTC, peppelinux commented
> > Please, add the normative text according to the non normative examples
> 
> Can you give an example? Originally there was no other additional text

During the weekly meeting we agreed that along with the non normative example we need to better clarify the beahviour of the implementations using normative language and clear definition about the requirements these must satisfy

therefore we decided that this PR requires normative language within the appropriate section describing the result represented in the non normative examples

2024-06-26 16:20 UTC, fmarino-ipzs approved these changes

2024-06-26 23:05 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +The request to the Wallet Provider endpoint in order to register the Wallet Instance MUST use the HTTP POST method with the parameters in the message body encoded in ``application/json`` format and t
```suggestion
In order to register the Wallet Instance, the request to the Wallet Provider MUST use the HTTP POST method. The parameters MUST be encoded in the `application/json` format and included in the message body. The following parameters MUST be provided:
```

I'd propose to give a name to the wallet registration endpoint in the wallet solution architecture

2024-06-26 23:07 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +      - It MUST be set to the unique identifier of the **Cryptographic Hardware Keys** in ``base64url`` encoded
```suggestion
      - It MUST be set with the unique identifier of the **Cryptographic Hardware Keys** and encoded in ``base64url``.
```

2024-06-26 23:09 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +The response, in case of success, from the Wallet Provider must necessarily be a 204 No content.
```suggestion
Upon successful registration of the Wallet Instance, the Wallet Provider MUST respond with a status code set to 204 (No Content).
```

2024-06-26 23:12 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +If the authentication is successful the http response code MUST be 200 OK.
```suggestion
**Step 18**: The response is returned by the Wallet Provider, if successful the HTTP response code MUST be set to 200 OK and contain the Wallet Attestation signed by the Wallet Provider. The Wallet Instance therefore performs security and integrity verification about the Wallet Attestation. 
```

2024-06-26 23:14 UTC, peppelinux commented on docs/en/wallet-attestation.rst
>      eyJhbGciOiJFUzI1NiIsInR5cCI6IndhbGx... redacted
```suggestion
    eyJhbGciOiJFUzI1NiIsInR5cCI6IndhbGx ... 
```

2024-06-27 07:11 UTC, merged