Req.4 Wallet Attestation Signature
italia/eidas-it-wallet-docs pull request #288
Opened 2024-05-24 13:06 UTC by SaraConsoliACN

This pull request aims to resolve issue #256,

2024-05-27 07:25 UTC, peppelinux requested changes

2024-05-27 07:25 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +- The Wallet Attestation MUST be signed by the same Wallet Provider that is authoritative for (thus has issued) that wallet, as indicated by the overseeing Accreditation Body/Authority, so that the A
```suggestion
- The Wallet Attestation MUST be signed by the Wallet Provider that has authority over and that is the owner of the Wallet Solution, as specified by the overseeing registration authority. This ensures that the Wallet Attestation uniquely links the Wallet Provider to this particular Wallet Instance.
```

2024-05-28 09:18 UTC, peppelinux approved these changes

2024-05-28 09:25 UTC, grausof approved these changes

2024-05-29 10:16 UTC, fmarino-ipzs approved these changes

2024-05-29 10:16 UTC, merged