Entities who can request WI revocation
italia/eidas-it-wallet-docs pull request #304
Opened 2024-06-04 10:03 UTC by cmarco0

This PR aims to solve #253

2024-06-12 08:19 UTC, peppelinux requested changes

2024-06-12 08:19 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +Taking as reference the ARF in `Section 6.5.4 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md#654-wallet-instance-management>`_ and
```suggestion
According to ARF, `Section 6.5.4 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md#654-wallet-instance-management>`_ and more specifically in `Topic 38 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/annexes/annex-2/annex-2-high-level-requirements.md#a2338-topic-38---wallet-instance-revocation>`_ the Wallet Instance can be revoked by the following entities:
```

I have removed "requested" because even the jurisdictional authorities can request the WI revocation to the wallet providers and or PID Providers

2024-06-17 11:15 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +  1. Holder
```suggestion
  1. Its owner, the User
```

2024-06-17 11:16 UTC, peppelinux approved these changes

2024-06-17 11:28 UTC, grausof commented
we still don't have the flow for the PID provider. I'd rule it out for now

2024-06-17 11:37 UTC, peppelinux commented
> we still don't have the flow for the PID provider. I'd rule it out for now

good catch, see the issue here: https://github.com/italia/eudi-wallet-it-docs/issues/317

2024-06-17 12:04 UTC, grausof approved these changes

2024-06-17 12:04 UTC, grausof commented on docs/en/wallet-attestation.rst
> +  3. PID Provider
```suggestion
```

2024-06-17 12:49 UTC, fmarino-ipzs approved these changes

2024-06-17 13:40 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +
```suggestion
3. PID Provider

```

2024-06-17 13:40 UTC, peppelinux commented on docs/en/wallet-attestation.rst
> +3. PID Provider
```suggestion
  3. PID Provider
```

2024-06-17 13:41 UTC, merged