Added ARF reference in PID claim
italia/eidas-it-wallet-docs pull request #305
Opened 2024-06-04 13:36 UTC by cmarco0

this commit aims to resolve the following issues:

- https://github.com/italia/eudi-wallet-it-docs/issues/261
- https://github.com/italia/eudi-wallet-it-docs/issues/262

2024-06-08 16:23 UTC, peppelinux commented
This PR doesn't resolve the mentioned issues, it only adds a reference to the ARF

2024-06-10 12:35 UTC, cmarco0 commented
> This PR doesn't resolve the mentioned issues, it only adds a reference to the ARF

Yes, I have added the references to the ARF where the PID data set schema is provided (PID Rulebook).

Then, in the table here [PID Claims](https://github.com/italia/eudi-wallet-it-docs/blob/versione-corrente/docs/en/pid-eaa-data-model.rst#pid-claims), the reference for family_name state as per [OpenID Connect Core 1.0 Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims):
Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters.

Additionally, in the PID Rulebook table [PID Rulebook](https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/annexes/annex-3/annex-3.01-pid-rulebook.md#232-overview), the Encoding format is tstr, referenced in [RFC 8610](https://www.rfc-editor.org/rfc/rfc8610.html). This format can accommodate multiple family names separated by space characters, as explained in the OpenID specification.

2024-06-12 08:14 UTC, peppelinux approved these changes

2024-06-12 08:15 UTC, peppelinux requested changes

2024-06-12 08:15 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The the PID attribute schema is defined by `ARF v1.4 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md#21-identification-and-authentic
```suggestion
The PID attribute schema, which encompasses all potential user data, is defined in `ARF v1.4 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md#21-identification-and-authentication-to-access-online-services>`_, and furthermore detailed in the `PID Rulebook <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/annexes/annex-3/annex-3.01-pid-rulebook.md#23-pid-attributes>`_.
```

2024-06-17 11:18 UTC, peppelinux commented on docs/en/pid-eaa-data-model.rst
> +The PID attribute schema, which encompasses all potential user data, is defined in `ARF v1.4 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/doc
```suggestion
The PID attribute schema, which encompasses all potential User data, is defined in `ARF v1.4 <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/arf.md#21-identification-and-authentication-to-access-online-services>`_, and furthermore detailed in the `PID Rulebook <https://github.com/eu-digital-identity-wallet/eudi-doc-architecture-and-reference-framework/blob/main/docs/annexes/annex-3/annex-3.01-pid-rulebook.md#23-pid-attributes>`_.
```

2024-06-17 11:18 UTC, peppelinux approved these changes

2024-06-17 11:29 UTC, grausof approved these changes

2024-06-17 12:04 UTC, fmarino-ipzs approved these changes

2024-06-17 13:54 UTC, merged