Added definition of Holder
italia/eidas-it-wallet-docs pull request #306
Opened 2024-06-04 15:26 UTC by cmarco0

holder is a more specific term to define the generic one "EUDIW user"

2024-06-12 08:13 UTC, peppelinux requested changes

2024-06-12 08:13 UTC, peppelinux commented on docs/en/defined-terms.rst
> +     - User that has activated and has full control of an instance of the EUDI wallet and the related Private Keys.
```suggestion
     - Natural or Legal person that receives Verifiable Credentials and has control over them to present them to the Verifiers as Presentations, using the Wallet. The Holder is the User in control of the Wallet.
```

2024-06-14 21:14 UTC, fmarino-ipzs approved these changes

2024-06-17 13:56 UTC, peppelinux commented on docs/en/defined-terms.rst
> +     - Natural or Legal person that receives Verifiable Credentials and has control over them to present them to the Verifiers as Presentations, using the Wallet. The Holder is the User in control of
```suggestion
     - Natural or Legal person that receives Verifiable Credentials from the Credential Issuers, manages the Verifiable Credentials within the Wallet, and presents them to Verifiers. The Holder is the User in control of the Wallet.
```

2024-06-17 13:56 UTC, peppelinux approved these changes

2024-06-17 13:59 UTC, grausof approved these changes

2024-06-17 14:04 UTC, merged