editorial: revocation request pop
italia/eidas-it-wallet-docs pull request #426
Opened 2024-09-30 08:17 UTC by peppelinux

This PR resolves https://github.com/italia/eudi-wallet-it-docs/issues/424

2024-10-01 08:12 UTC, grausof approved these changes

2024-10-01 08:39 UTC, m-basili requested changes

2024-10-01 08:39 UTC, m-basili commented on docs/en/revocation-lists.rst
> +**Step 2 (Revocation Assertion Request verification)**: The Credential Issuer that receives the Status Assertion Request object MUST validate that the Wallet Instance making the request is authorized
```suggestion
**Step 2 (Status Assertion Request verification)**: The Credential Issuer that receives the Status Assertion Request object MUST validate that the Wallet Instance making the request is authorized to request Status Assertions. Therefore the following requirements MUST be satisfied:
```

2024-10-02 09:04 UTC, m-basili approved these changes

2024-10-02 09:04 UTC, merged