breaking change: added credential_status_detail in the status assertion
italia/eidas-it-wallet-docs pull request #432
Opened 2024-10-01 11:54 UTC by m-basili

This PR solves #401.

2024-10-01 15:00 UTC, peppelinux commented on docs/en/pid-eaa-entity-configuration.rst
> +    - JSON object that outlines the details of each validity status supported by the PID/(Q)EAA Provider related to the credentials issued. It contains ``Display`` array containing a list of states w
```suggestion
    - JSON object that outlines the details of each validity status supported by the PID/(Q)EAA Provider related to the Credentials issued. It contains ``Display`` array containing a list of states with the corresponding descriptions and language identifiers. The parameter that MUST be included are:
```

2024-10-01 15:01 UTC, peppelinux commented on docs/en/pid-eaa-entity-configuration.rst
> +        - **state**: String value of a credential status supported.
```suggestion
        - **state**: String value of a Credential status supported.
```

2024-10-01 15:01 UTC, peppelinux commented on docs/en/revocation-lists.rst
> +      - Object containing detailed information about the real status of the credential. IT MUST contains ``state`` and related ``description`` claims that MUST be set with one of the values defined i
```suggestion
      - Object containing detailed information about the real status of the Credential. It MUST contains ``state`` and related ``description`` claims that MUST be set with one of the values defined in the *credential_status_detail_supported* mapped in the Credential Issuer Metadata.
```

2024-10-01 15:02 UTC, peppelinux commented on docs/en/revocation-lists.rst
> +      - REQUIRED if **credential_status_validity** is set to `false`. Object containing detailed information about the real status of the credential. IT MUST contains ``state`` and related ``descript
```suggestion
      - REQUIRED if **credential_status_validity** is set to `false`. Object containing detailed information about the real status of the Credential. IT MUST contains ``state`` and related ``description`` claims that MUST be set with one of the values defined in the *credential_status_detail_supported* mapped in the Credential Issuer Metadata.
```

2024-10-01 15:02 UTC, peppelinux commented on examples/ec-eaa.json
> +                    "description": "La credenziale non è più utilizzabile in quanto è stata revocata. Questo stato è irreversibile",
```suggestion
                    "description": "La Credenziale non è più utilizzabile in quanto è stata revocata. Questo stato è irreversibile",
```

2024-10-01 15:02 UTC, peppelinux approved these changes
@m-basili please accept my editorials.

2024-10-01 20:39 UTC, grausof approved these changes

2024-10-02 09:15 UTC, peppelinux commented on docs/en/revocation-lists.rst
> +      - Object containing detailed information about the real status of the Credential. It MUST contains ``state`` and related ``description`` claims that MUST be set with one of the values defined i
```suggestion
      - Object containing detailed information about the real status of the Credential. It MUST contains ``state`` and related ``description`` parameters that MUST be set with one of the values defined in the *credential_status_detail_supported* mapped in the Credential Issuer metadata.
```

2024-10-02 09:16 UTC, peppelinux commented on docs/en/revocation-lists.rst
> +      - REQUIRED if **credential_status_validity** is set to `false`. Object containing detailed information about the real status of the Credential. IT MUST contains ``state`` and related ``descript
```suggestion
      - REQUIRED if **credential_status_validity** is set to `false`. Object containing detailed information about the real status of the Credential. IT MUST contains ``state`` and related ``description`` parameters that MUST be set with one of the values defined in the *credential_status_detail_supported* mapped in the Credential Issuer metadata.
```

2024-10-02 09:21 UTC, peppelinux requested changes
Any new proposal about ietf oauth status assertion MUST be developed in the related I-D, here:

https://github.com/peppelinux/draft-demarco-oauth-status-assertions

2024-10-04 09:00 UTC, fmarino-ipzs approved these changes

2024-10-07 08:11 UTC, grausof approved these changes

2024-10-08 16:40 UTC, m-basili commented
waiting for https://github.com/peppelinux/draft-demarco-oauth-status-assertions/pull/87 approval.

2024-10-16 08:22 UTC, grausof approved these changes

2024-10-16 09:15 UTC, peppelinux approved these changes

2024-10-16 09:15 UTC, merged