Update wallet-instance-attestation.rst
italia/eidas-it-wallet-docs pull request #50
Opened 2023-07-04 16:00 UTC by ruphy

Proofreading

2023-07-04 16:39 UTC, peppelinux requested changes

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +To meet these requirements, it is necessary for each Wallet Instance to issue a certificate of conformity, guaranteeing its security and compliance with the Trust Model.
```suggestion
To meet these requirements, it is necessary for each Wallet Instance to issue an attestation of conformity, guaranteeing its security and compliance with the Trust Model.
```

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +To meet these requirements, it is necessary for each Wallet Instance to issue a certificate of conformity, guaranteeing its security and compliance with the Trust Model.
I would prevent the term certificate since it may point to X.509 certificates

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +This certificate, called the **Wallet Instance Attestation**, must be electronically signed by its issuer.
```suggestion
This verifiable attestation, called the **Wallet Instance Attestation**, must be electronically signed by its issuer.
```

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> + **Message 1**: The User initializes the Wallet Instance. In particular, this process happens after the Wallet Instance installation and after the expiration of the Wallet Instance Attestation is lau
```suggestion
 **Message 1**: The User initializes the Wallet Instance. In particular, this process happens after the Wallet Instance installation and after the expiration of the Wallet Instance Attestation is launched and every time the User wants to request or present a credential.
```

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> + **Message 1**: The User initializes the Wallet Instance. In particular, this process happens after the Wallet Instance installation and after the expiration of the Wallet Instance Attestation is lau
since the attributes in the credential are disclosed, while the entire credential is presented in its original status

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +- **Message 4**: The Wallet Instance verifies that the Wallet Provider is trustworthy by resolving the provider's trust chain up to the anchor
```suggestion
- **Message 4**: The Wallet Instance verifies that the Wallet Provider is trustworthy by resolving the provider's trust chain up to the Trust Anchor.
```

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +- **Message 5-7**: The Wallet Instance instantiates a new key pair on its TEE and requests a ``nonce`` from the Wallet Provider (as a measure against replay attacks).
```suggestion
- **Message 5-7**: The Wallet Instance creates a new key pair and requests a ``nonce`` from the Wallet Provider (as a measure against replay attacks).
```

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +- **Message 5-7**: The Wallet Instance instantiates a new key pair on its TEE and requests a ``nonce`` from the Wallet Provider (as a measure against replay attacks).
` and requests a ``nonce`` from the Wallet Provider (as a measure against replay attacks)` @grausof this is under discussion, would it be better to move into the related PR for that? (next milestone?)

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +- **Message 8**: The Wallet Instance generates a Wallet Instance Attestation Request, in JWS format, signed with the private key associated with the public key for which it wants to obtain the attest
```suggestion
- **Message 8**: The Wallet Instance generates a Wallet Instance Attestation Request, in JWS format, signed with the private key associated with the public key for which it wants to obtain the attestation.
```

2023-07-04 16:39 UTC, peppelinux commented on docs/en/wallet-instance-attestation.rst
> +- **Message 8**: The Wallet Instance generates a Wallet Instance Attestation Request, in JWS format, signed with the private key associated with the public key for which it wants to obtain the attest
not required here

2023-07-04 23:44 UTC, peppelinux approved these changes

2023-07-05 16:00 UTC, fmarino-ipzs approved these changes

2023-07-05 16:01 UTC, grausof approved these changes
LGTM

2023-07-05 16:01 UTC, peppelinux approved these changes

2023-07-05 16:01 UTC, merged