contribute.rst
italia/eidas-it-wallet-docs pull request #61
Opened 2023-07-10 09:42 UTC by MartaS-Easygov

## Title

## Content

## Review

- [x] Ensure your files are written following RST specs (*not MD!*)
- [ ] Italian version
- [x] English version
- [ ] Example files 
- [x] Ask for review

2023-07-10 12:47 UTC, peppelinux requested changes

2023-07-10 12:47 UTC, peppelinux commented on docs/en/contribute.rst
> +- **Developers Italia Slack channel**. Slack is a messaging app for business that connects people to the information they need. *Developers Italia* is an open community based on the participation and
please add an invitation badge, as already in the README (but in markdown, please translate to RST accordingly)

````
[![Get invited](https://slack.developers.italia.it/badge.svg)](https://slack.developers.italia.it/)
````

2023-07-10 15:05 UTC, fmarino-ipzs approved these changes

2023-07-10 16:04 UTC, peppelinux requested changes

2023-07-10 16:04 UTC, peppelinux commented on docs/en/contribute.rst
> +Hence, stakeholders and members of the national and international community are encouraged, and more than welcome, to contribute to the content and editing of these technical rules.
```suggestion
Hence, stakeholders and members of the national and international community are encouraged, and more than welcome, to contribute to the content of these technical rules.
```

2023-07-10 16:04 UTC, peppelinux commented on docs/en/contribute.rst
> +Here are some tools that you can use to submit your contribution:
```suggestion
Below are listed the ways that can be used to give contributions to this project:
```

2023-07-10 16:04 UTC, peppelinux commented on docs/en/contribute.rst
> +- **Developers Italia Slack channel**. Slack is a messaging app for business that connects people to the information they need. *Developers Italia* is an open community based on the participation and
```suggestion
- **GitHub issues**. By opening an issue it is possible to ask clarifications, propose enhancements or notify editorial typos. To indicate that work is in progress is possible to link an issue to a pull request;
- **Pull requests**. These represents active contributions to the project, where a discussion in the form of issues has already taken place. Once a pull request is opened, some discussions and reviews of the proposed changes take place, before the changes are merged into the main branch (`versione-corrente`);
- **Developers Italia Slack channel**. Slack is a messaging app for business that connects people to the information they need. *Developers Italia* is an open community based on the participation and contribution of public administrations, developers, technicians, students and citizens. *Developers Italia* started a Slack channel that [everyone can join for free](https://slack.developers.italia.it/), where you can discover all their activities and participate in the discussion.
```

2023-07-12 18:34 UTC, peppelinux approved these changes

2023-07-12 18:34 UTC, merged